Total stream USD value
Ricochet-Exchange/ricochet-frontend pull request #154
Opened 2021-12-22 23:46 UTC by elvijsTDL

2021-12-23 15:08 UTC, mikeghen commented
Can you have the USD value up top in black and blue, then in smaller font size under have the TVS in the native token, sort of like how its done here
<img width="397" alt="Screen Shot 2021-12-23 at 10 06 59 AM" src="https://user-images.githubusercontent.com/5077880/147258491-e44bceec-e346-49bc-83a5-f8a4a1374293.png">

2021-12-23 15:09 UTC, mikeghen requested changes
Nice work otherwise

2021-12-24 02:19 UTC, elvijsTDL commented
Done @mikeghen 

![Screenshot 2021-12-24 at 04 18 00](https://user-images.githubusercontent.com/77115130/147307679-de9836a6-27ee-41e4-b8bd-e4c6089c9ed2.png)
![Screenshot 2021-12-24 at 04 19 03](https://user-images.githubusercontent.com/77115130/147307766-6e447aa0-4e94-4aa9-8507-6979eab6af9b.png)

2021-12-25 15:43 UTC, mikeghen commented on src/components/layout/PanelChange/index.tsx
> +    return (parseFloat(flow as string) * coingeckoPrice).toFixed(2);
if we arent going to do the K,M abbreviations, can we at least not show the decimal cents? Here, one has no cents after the decimal, another has just 1 number after the decimal, and another has 2 numbers after the decimal
<img width="172" alt="Screen Shot 2021-12-25 at 9 28 16 AM" src="https://user-images.githubusercontent.com/5077880/147388558-8653dd74-28c4-40ae-95e6-9cc100de80d5.png">

2021-12-25 15:44 UTC, mikeghen requested changes
just can we remove the decimals

2021-12-26 16:11 UTC, elvijsTDL commented
@mikeghen Removed the cents from the USD price, left them at token amounts, because they add up to a bunch of value for tokens like ETH
![Screenshot 2021-12-26 at 18 11 21](https://user-images.githubusercontent.com/77115130/147413866-f144b711-97c0-43c2-8889-9b16b7cef0a6.png)

2021-12-26 16:16 UTC, merged