Redirecting vault page on first load to invest page
Ricochet-Exchange/ricochet-frontend pull request #533
Opened 2022-03-01 00:07 UTC by Seroxdesign

Issue:

When refreshing window or starting app on Vault page user is unable to access their information. Even if the users' metamask is connected to the website / the user clicks the connect button.

Solution:

In MainRouter I added a useEffect hook to check the users' current location, if the user loaded the page on Vault then we will redirect the user to invest page and refresh the page.

This all happens within 0.5s so it shouldn't be a problem for performance or data usage.

2022-03-01 14:47 UTC, abhisheknaiidu requested changes

2022-03-01 14:47 UTC, abhisheknaiidu commented on src/containers/MainRouter/index.tsx
> +      history.push('/');
instead of `history.push('/')` , let's add Routes from `constants` file => `history.push(Routes.Invest)`

2022-03-01 15:09 UTC, abhisheknaiidu approved these changes
works perfectly now! ✨

2022-03-02 19:40 UTC, Seroxdesign commented
@mikeghen Can you please review this, it stops the app from breaking if user tries to load from Vault page (Currently an issue in app.ricochet)

2022-03-03 22:37 UTC, mikeghen commented
Hm, is this the right thing to do though? Should we really redirect someone when they refresh on the Vault page? I have seen this issue but I would think the right thing to do would be to fix it so when they're on the vault page it either loads their vaults or it says you don't have any vaults yet

2022-03-03 23:02 UTC, Seroxdesign commented
No problem, will re-work this issue then.

2022-03-05 15:26 UTC, closed without merging