feat: recent stream activity.
Ricochet-Exchange/ricochet-frontend pull request #546
Opened 2022-03-03 11:24 UTC by zhyd1997

Fixes #393

2022-03-03 15:07 UTC, mikeghen requested changes
I also think there's some missing icons from the frontend
<img width="1490" alt="Screen Shot 2022-03-03 at 10 06 25 AM" src="https://user-images.githubusercontent.com/5077880/156592130-097f0329-5801-4260-8ffc-cce79dcbf4ee.png">

2022-03-03 15:08 UTC, mikeghen commented
I left two comments, otherwise I think this is really good so thank you for taking a look at it @zhyd1997

2022-03-03 15:08 UTC, bigint commented on package.json
> +    "ethers": "^5.5.2",
+1 if we downgrade this ENS name will not work 😕

2022-03-03 19:42 UTC, zhyd1997 commented on package.json
> +    "ethers": "^5.5.2",
@mikeghen
not manually downgraded, maybe need update with v2 branch.

2022-03-03 19:44 UTC, zhyd1997 commented
> I also think there's some missing icons from the frontend <img alt="Screen Shot 2022-03-03 at 10 06 25 AM" width="1490" src="https://user-images.githubusercontent.com/5077880/156592130-097f0329-5801-4260-8ffc-cce79dcbf4ee.png">

I have added all token address listed in `polygon-config.js`,  could you tell me which token you're using that missed in this PR?

2022-03-03 20:55 UTC, zhyd1997 commented
Updated: f37fb3b

Try again and see if the token displays.

2022-03-03 22:33 UTC, mikeghen approved these changes
Very good! great addition

2022-03-03 22:34 UTC, mikeghen commented
@zhyd1997 there's one merge conflict, not sure what it is so have a look

2022-03-03 22:41 UTC, zhyd1997 commented
Conflicts resolved!

2022-03-03 23:02 UTC, zhyd1997 commented
I need to regenerate fonts, give me 10 minutes.

2022-03-03 23:30 UTC, Seroxdesign commented
This is really good! Great work

2022-03-04 22:48 UTC, zhyd1997 commented
@mikeghen If you have any questions about the OR, please let me know

2022-03-05 00:39 UTC, zhyd1997 commented
Additional Checklist:

- [ ] default token image
- [ ] query unlisted token name
- [ ] filter out zeroAddress (0x0000...)
- [ ] support copy address
- [ ] show streaming market if possible

@mikeghen @elvijsTDL

2022-03-06 14:24 UTC, Seroxdesign commented
This is really good!  Really nice to see how you used the superfluid sdk.

2022-03-06 19:32 UTC, zhyd1997 commented
Converting to draft PR again to consider if there a way to catch the stream that started from the Ricochet market.

2022-03-07 01:46 UTC, zhyd1997 commented
We can track started stream (or stop fixed stream) on our Launchpad according to the`flowsRecieved` and find it by this code:
https://github.com/Ricochet-Exchange/ricochet-frontend/blob/9a66f688f6eaef96a048e85cb59548594395e41d/src/store/main/selectors.ts#L7

just like the PR comments:
<img width="677" alt="PR 1130 comments" src="https://user-images.githubusercontent.com/31362988/156953912-bccbda53-859f-4151-965b-868cbe971922.png">

But we will miss it if the stream is stopped, so I tried my best and it's hard to track the market by stream information.

2022-03-07 17:14 UTC, mikeghen commented
This looks good @zhyd1997, I will merge it :+1:

2022-03-07 17:14 UTC, merged