List DaiEth and RicUsdc two way markets
Ricochet-Exchange/ricochet-frontend pull request #560
Opened 2022-03-05 00:10 UTC by elvijsTDL

Fixes #559 and #558

2022-03-05 00:12 UTC, elvijsTDL commented
Distributions show up 52 years ago because there have never been one yet, will leave the streams open , but going off for now
![Screenshot 2022-03-05 at 02 10 38](https://user-images.githubusercontent.com/77115130/156858383-a921a026-3b47-423d-8df9-ff7652b6c6c0.png)

2022-03-05 00:33 UTC, mikeghen approved these changes

2022-03-05 00:33 UTC, mikeghen commented on src/constants/flowConfig.ts
> +  },
I think these might be off, I tried to open a stream USDC>>RIC and got this error:
<img width="1325" alt="Screen Shot 2022-03-04 at 7 31 57 PM" src="https://user-images.githubusercontent.com/5077880/156859472-ebf90ea0-3fec-40c5-9041-6d628112d8d9.png">

2022-03-05 00:33 UTC, mikeghen commented on src/constants/flowConfig.ts
> +  },
https://dashboard.tenderly.co/tx/polygon/0x1fc6c3f5b048ecf52159e45a570d5661fa366c8ea0064f2391a443e09f59032a

2022-03-05 00:34 UTC, mikeghen requested changes
I think the index might be messed up on the USDC>>RIC side of the exchange

2022-03-07 16:15 UTC, mikeghen requested changes
Can you change the ETH<>DAI market to this address: 0xEAA1d76D0aB8d0cab426e7427c472C638cFc5EA1

The previous one had an issue with the lastDistributedAt

2022-03-07 16:29 UTC, mikeghen commented
@elvijsTDL, let me know when you get a chance to review the requested changes

2022-03-09 14:51 UTC, mikeghen requested changes
@elvijsTDL, I just deployed the MATIC<>USDC market: 0x7688f3efA3A19948b07c26B5B72F67a42d102C83, could you add this too?

2022-03-09 15:04 UTC, mikeghen commented
@elvijsTDL also added another $500 bounty for listing MATIC<>USDC :+1: so this PR with all the markets would be a $1500 bounty 
<img width="358" alt="Screen Shot 2022-03-09 at 10 03 22 AM" src="https://user-images.githubusercontent.com/5077880/157468674-4d685ac6-bd57-4192-8e03-4482cfb24bc2.png">

2022-03-09 20:28 UTC, mikeghen commented
@elvijsTDL the MATIC<>DAI contract address: 0xbb131E3Cd2FadE7f387c2024F04F33Ed5e6c5101

2022-03-10 20:03 UTC, mikeghen approved these changes
Well done @elvijsTDL 
<img width="1321" alt="Screen Shot 2022-03-10 at 11 50 25 AM" src="https://user-images.githubusercontent.com/5077880/157745405-27843844-670d-40bb-838a-c2983dffe4b7.png">
<img width="1330" alt="Screen Shot 2022-03-10 at 11 50 00 AM" src="https://user-images.githubusercontent.com/5077880/157745412-f5bddf9a-e299-4e79-ba0b-c678a0a0387c.png">

2022-03-10 20:03 UTC, merged