fix: pulled price from sushi lps.
Ricochet-Exchange/ricochet-frontend pull request #686
Opened 2022-05-27 13:32 UTC by zhyd1997

Fixes #684

2022-05-27 13:47 UTC, mikeghen requested changes
The price shouldnt show up on the launchpad

<img width="789" alt="Screen Shot 2022-05-27 at 9 44 29 AM" src="https://user-images.githubusercontent.com/5077880/170711818-6e35d77f-562d-42b9-b089-145507533866.png">

Could you match the style from the launchpad? Which puts the price above the market using a smaller font. Also use `@ 0.03 USDC/RIC` like it is on the launchpad, use @ symbol instead of 🚀 

Include prices for all the markets

<img width="421" alt="Screen Shot 2022-05-27 at 9 44 43 AM" src="https://user-images.githubusercontent.com/5077880/170712189-21e691e3-4f0a-4066-b307-31c1a66eb9fb.png">

2022-05-27 14:51 UTC, mikeghen requested changes
1. Can you make the font a little smaller?
2. It looks like every price is the same
<img width="405" alt="Screen Shot 2022-05-27 at 10 49 29 AM" src="https://user-images.githubusercontent.com/5077880/170723895-645bb8da-4d84-460a-a36f-94ac8b65d9c5.png">

2022-05-27 14:52 UTC, zhyd1997 commented
@mikeghen do we need other pair price 👀

2022-05-27 19:32 UTC, mikeghen commented
> @mikeghen do we need other pair price 👀

Yes

2022-05-28 12:31 UTC, zhyd1997 commented on src/components/common/Price/index.tsx
> +	// FIXME: add other pools
@mikeghen 

need other liquidity pool contract addresses here.

2022-06-06 11:18 UTC, Seroxdesign commented
Any progress on this @zhyd1997

2022-06-06 11:53 UTC, zhyd1997 commented
Need @mikeghen response.

2022-06-08 15:17 UTC, mikeghen commented
Liquidity pools, some are quickswap:

RIC<>USDC, Sushi: 0xDBF5d66d77a83B96763c965D193D0fdD1f8A184B
ETH<>USDC, Sushi: 0x34965ba0ac2451A34a0471F04CCa3F990b8dea27
WBTC<>USDC, Sushi: 0xD02b870c556480491c70AaF98C297fddd93F6f5C 
MATIC<>USDC, Quickswap: 0x6e7a5FAFcec6BB1e78bAE2A1F0B612012BF14827
ETH<>DAI, Sushi: 0x6FF62bfb8c12109E8000935A6De54daD83a4f39f
WBTC<>DAI, Sushi: 0x7a1d5E67c3a273274766E241363E3E98e721E456
MATIC<>DAI, Quickswap: 0xEEf611894CeaE652979C9D0DaE1dEb597790C6eE

2022-06-08 18:51 UTC, mikeghen commented
Looks good but if its 0 like this could we just show `< 0.001 ETH/USDC`?
<img width="325" alt="Screen Shot 2022-06-08 at 2 50 16 PM" src="https://user-images.githubusercontent.com/5077880/172693924-bc0b9020-943c-4bdb-9303-615497c967e8.png">

2022-06-08 22:49 UTC, zhyd1997 commented
<img width="667" alt="< 0.001" src="https://user-images.githubusercontent.com/31362988/172730215-0de5d34c-db0b-4e89-b70f-260306b90160.png">

2022-06-09 13:03 UTC, mikeghen approved these changes

2022-06-09 13:03 UTC, merged

2022-06-09 13:03 UTC, mikeghen commented
good work @zhyd1997 👏