fix: enhanced wallet page.
Ricochet-Exchange/ricochet-frontend pull request #796
Opened 2022-09-18 06:19 UTC by zhyd1997

Fixes #793

2022-09-18 12:17 UTC, zhyd1997 commented
@mikeghen PTAL

2022-09-18 14:07 UTC, mikeghen requested changes
It looks like the "Ricoceht balance" might not be calculating correctly:
<img width="1441" alt="Screen Shot 2022-09-18 at 10 05 48 AM" src="https://user-images.githubusercontent.com/5077880/190911155-f449eb59-429d-4595-bebf-a06c6675e43d.png">

2022-09-19 03:54 UTC, mikeghen approved these changes

2022-09-19 03:58 UTC, merged

2022-09-19 03:58 UTC, mikeghen commented
Great work @zhyd1997 👏