Aggregate rewards
Ricochet-Exchange/ricochet-frontend pull request #828
Opened 2022-11-24 19:18 UTC by Seroxdesign

Made aggregator for RIC rewards
atm there's a bug where it won't aggregate, the ground work has all been set up in redux, though. should be a simply fix

2022-11-24 19:18 UTC, Seroxdesign commented
@hrishibhattu @abhisheknaiidu 

This is 90% done, minor bug where the numbers won't add up and only last value is set. If you'd like to finish it you can claim the bounty on it,

2022-11-25 20:56 UTC, mikeghen requested changes
I think you're incrementing the rate every time I change app pages, the rate was correct, then I went to the active streams page, the rate went up, then I went to launchpad, went up again. What started as like 1100 turned into like 5000. Check you're not constantly adding more to the reward on page loads or something.

Also, do a quick styling on this and itll be good to go, just say "Rewards: X RIC/mo."

2022-11-27 17:53 UTC, Seroxdesign commented
@mikeghen ready for review

2022-11-28 12:50 UTC, mikeghen requested changes
this is still an issue for me. visit the active streams page that will do it:
> I think you're incrementing the rate every time I change app pages, the rate was correct, then I went to the active streams page, the rate went up, then I went to launchpad, went up again. What started as like 1100 turned into like 5000. Check you're not constantly adding more to the reward on page loads or something.

2022-12-04 20:47 UTC, mikeghen commented
Looks good but still increases when I go from Markets to Active Stream page, I have these open:
<img width="1271" alt="Screen Shot 2022-12-04 at 3 47 24 PM" src="https://user-images.githubusercontent.com/5077880/205514689-2f1382b1-c9aa-4e1f-a7e8-79b13727c523.png">

2022-12-07 19:32 UTC, mikeghen requested changes
I get the following error, I think you editted CORS rules:
```
getCoingeckoPrices.ts:39 TypeError: Failed to fetch
    at getCoingeckoPrices.ts:30:9
    at d (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.next (regeneratorRuntime.js:117:21)
    at r (asyncToGenerator.js:3:20)
    at c (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21:12
    at dd (main.5f2b6c82.chunk.js:1:277565)
    ...
/#/invest/rex-market:1 Access to fetch at 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=USD&ids=dai,usd-coin,weth,wrapped-bitcoin,matic-network,richochet,weth,usd-coin,wrapped-bitcoin' from origin 'https://ricochet-frontend-git-fork-seroxdesign-aggregat-b26cc6-mikeghen.vercel.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

2022-12-07 20:10 UTC, mikeghen requested changes
I tried to create a new stream but the input box doesnt accept my input
<img width="512" alt="Screen Shot 2022-12-07 at 3 08 31 PM" src="https://user-images.githubusercontent.com/5077880/206285129-5c94484a-b585-42a3-b108-7ea1f44bcda3.png">

2022-12-08 09:27 UTC, Seroxdesign commented on src/containers/main/InvestContainer/InvestMarket.tsx
> +	useEffect(() => {
This useEffect has a param of aggregatedRewards.

But in order to make sure it works properly after doing a state change I need to set aggregatedRewards to [0] which retriggers useEffect

2022-12-08 16:35 UTC, abhisheknaiidu requested changes

2022-12-08 16:35 UTC, abhisheknaiidu commented on src/containers/main/InvestContainer/InvestMarket.tsx
> +			setAggregatedRewards([0]);
you need to add `return` after this, otherwise it will go on a loop.

2022-12-11 18:45 UTC, Seroxdesign commented
PR has been merged into #831 will be closing this now

2022-12-11 18:45 UTC, closed without merging