Refactor Polygon Config - To Merge
Ricochet-Exchange/ricochet-frontend pull request #833
Opened 2022-12-21 17:25 UTC by Seroxdesign

Fixes #

Changes proposed in this pull request:

    Refactored and commented Polygon config
    Removing unused contracts
    Debugging some errors with ASYNC

2022-12-21 17:52 UTC, mikeghen commented on src/api/ethereum.ts
> -					}),
Please leave this since this approval sequence is needed for REX LP, I will come through soon to work on this since I'm relaunching REX LP

2022-12-21 17:55 UTC, mikeghen requested changes
one change requested

2022-12-21 17:55 UTC, mikeghen commented on src/api/ethereum.ts
> -					}),
Bring this back, change from SUSHIx to use ETHx for now since youre removing sushix. Ill bring back REX LP soon

2022-12-22 16:27 UTC, mikeghen requested changes
Somewhere this is getting stuck for me, I'm not sure where but it looks like its subgraph stuff
<img width="1472" alt="Screen Shot 2022-12-22 at 11 26 49 AM" src="https://user-images.githubusercontent.com/5077880/209178804-33cb89f8-a0a9-43a5-b5a9-2c5d38ce66dc.png">

2022-12-22 17:31 UTC, Seroxdesign commented
> Somewhere this is getting stuck for me, I'm not sure where but it looks like its subgraph stuff <img alt="Screen Shot 2022-12-22 at 11 26 49 AM" width="1472" src="https://user-images.githubusercontent.com/5077880/209178804-33cb89f8-a0a9-43a5-b5a9-2c5d38ce66dc.png">

When we set up:

```
await framework.idaV1.approveSubscription({
      superToken: WETHx,
      indexId: '1',
      publisher: exchangeAddress,
      userData,
      overrides: {
	      maxFeePerGas,
	      maxPriorityFeePerGas,
      },
  }),
```

Something causes the app to crash I assume approveSubscription is not expecting WETHx, so I tried WBTCx, same issue.

I commented out the code so it's available for you whenever you're ready to add rexETHLP.

If there's no other issue I will be moving on to the next task and clean up ethereum.ts

2022-12-23 15:09 UTC, mikeghen approved these changes
:+1: Thank you

2022-12-26 10:29 UTC, merged