update
Ricochet-Exchange/ricochet-frontend pull request #854
Opened 2023-01-21 03:14 UTC by mindsgn

Fixes #

**Changes proposed in this pull request:**
I Added Exchange Rates for ibAlluoX tokens
-
-
-

2023-01-21 16:20 UTC, mikeghen requested changes
Looking good, could you make sure that the ibAlluoX tokens rate is being used in these calculations? 1804 ibAlluoUSD I think is worth more that 1801 USDC
<img width="1214" alt="Screen Shot 2023-01-21 at 11 22 06 AM" src="https://user-images.githubusercontent.com/5077880/213876271-ff7dd60a-7236-4a26-9b18-81b00e77b6a1.png">

2023-01-23 09:52 UTC, mindsgn commented
@mikeghen whats the best way to calculate this? should I still use iballuoX price = ibAlluoX.growingRatio() * X.price

2023-01-23 16:41 UTC, mikeghen commented
@mindsgn I think the preview broke, it might have to do with your last commit

2023-01-25 13:59 UTC, mikeghen commented
@mindsgn the preview is still broken here

2023-02-06 12:19 UTC, Seroxdesign commented
This will be closed due to inactivity.

2023-02-22 20:31 UTC, mikeghen submitted a review, later dismissed
Exchange rates look good! But you lost the rates for the ETH and BTC, see they are `-`
<img width="358" alt="Screen Shot 2023-02-22 at 3 30 47 PM" src="https://user-images.githubusercontent.com/5077880/220751937-85825139-e433-40bf-8e08-d1d215e7d5cf.png">

2023-02-24 12:56 UTC, 0xSero commented
Requesting changes

2023-02-24 13:11 UTC, Seroxdesign requested changes

2023-02-24 13:11 UTC, Seroxdesign commented on src/components/common/Price/index.tsx
> +						coinA.includes(Coin.IbAlluoBTC) ||
Lots of if statements, nested as well. Is it possible to make thing into a switch statement, or at least use inverted if statements to avoid nesting

2023-02-24 13:11 UTC, Seroxdesign commented on src/components/layout/CoinRateForm/index.tsx
> +							isLoading ||
Can we move this logic into a function, then place the function directly in disabled, this will keep the logic and UI components a bit decoupled

2023-02-24 13:11 UTC, Seroxdesign commented on src/components/layout/PanelChange/index.tsx
> +	function isIbAlluo(coinA: Coin, coinB: Coin, totalFlow: string) {
Can you improve the name of this function I'm not sure what it does by reading the name

2023-02-24 13:11 UTC, Seroxdesign commented on src/components/layout/PanelChange/index.tsx
> +			if (tokenAddress !== '') {
if !tokenAddress works just as well as tokenAddress !== '' saves a few chars and is cleaner

2023-02-24 13:11 UTC, Seroxdesign commented on src/components/layout/PanelChange/index.tsx
> +						growthRatioPrice = data;
Why do you need to assign  ```growthRatioPrice = data``` then setSIbAlluoFlow? you can simply ``` setSIbAlluoFlow(data) ```

2023-02-24 13:11 UTC, Seroxdesign commented on src/components/layout/PanelChange/index.tsx
> +											<>{`$${personalFlow && getFlowUSDValue(personalFlow)} ${t('per month')}`}</>
Why are you using fragments here? Is it required? Just adds extra dom elements and slows things down

2023-02-24 13:11 UTC, Seroxdesign commented on src/components/layout/CoinRateForm/index.tsx
> +									{` ${(
Can we bind this logic to a variable and use that in <span>? Again decoupling logic from UI components

2023-02-24 13:11 UTC, Seroxdesign commented on src/components/common/Price/index.tsx
> +			if (data?.error || data.data === undefined) {
!data.data is better

2023-02-24 13:11 UTC, Seroxdesign commented on src/components/common/Price/index.tsx
> +										[`${coinA}-${coinB}`]: growthRatioPrice,
What's the logic with return here?

2023-02-24 13:11 UTC, Seroxdesign commented on src/components/common/Price/index.tsx
> +					if (tokenAddress !== '') {
tokenAddress instead of !== ''

2023-02-24 13:11 UTC, Seroxdesign commented on src/components/common/Price/index.tsx
> +						if (tokenAddress !== '') {
if (tokenAddress) is better

2023-03-03 11:13 UTC, Seroxdesign commented
@mindsgn if you're not working on this I'll be closing it

2023-03-06 15:27 UTC, mindsgn commented
@Seroxdesign I will make changes asap

2023-03-16 12:57 UTC, Seroxdesign commented on src/components/common/Price/index.tsx
> +			if (data?.error || data.data === undefined) {
!data.data

2023-03-16 12:57 UTC, Seroxdesign commented on src/components/layout/CoinRateForm/index.tsx
> +							isLoading ||
not been resolved

2023-03-16 12:57 UTC, 0xSero commented on src/components/layout/CoinRateForm/index.tsx
> +									{` ${(
not been resolved

2023-04-14 17:00 UTC, mikeghen commented
Im going to close this its too far out of date now, consider reopening it @mindsgn if you can finished it.

2023-04-14 17:00 UTC, closed without merging