chore: copy change
Ricochet-Exchange/ricochet-frontend pull request #898
Opened 2023-04-11 20:47 UTC by abhisheknaiidu

2023-04-14 16:13 UTC, mikeghen commented
@abhisheknaiidu can you change this so it only displays when the users balance is 0?

2023-04-14 16:14 UTC, mikeghen requested changes
Only show this message when the balance is 0, replace "money" with tokens as its a more accurate term for what those are.

2023-04-15 12:56 UTC, mikeghen submitted a review, later dismissed

2023-04-15 12:56 UTC, mikeghen commented on src/components/layout/CoinRateForm/index.tsx
> +						<span className={styles.depositTooltip_span}>Not enough money, deposit in wallet page </span>
could you just replace "money" with "tokens"

2023-04-20 15:11 UTC, Seroxdesign approved these changes

2023-04-20 15:11 UTC, merged